### ISSUE TITLE
./game/cs2.sh doesnt exist

### ISSUE THREAD

**Issue by Keiran-brooks** [1zc/CS2-Pterodactyl#50] opened 2024-08-12 02:09 UTC
I am running Ubuntu jammy 22.04 x86_64 and it cant find cs2.sh
```
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1721172922
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Please use force_install_dir before logon!
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '730' state is 0x202 after update job.
:/home/container$ ./game/cs2.sh -dedicated +ip 0.0.0.0 -port 27015 +map de_dust2 -maxplayers 32 +sv_setsteamaccount [REDACTED]
/entrypoint.sh: line 99: ./game/cs2.sh: No such file or directory
container@pterodactyl~ Server marked as offline...
```

**Comment by 1zc** [comment] 2024-08-12 15:04
Your install failed due to an error. 
```
Error! App '730' state is 0x202 after update job.
```
I believe `0x202` usually means you're out of disk space, I recommend taking a look at your host

**Comment by csd4ni3l** [comment] 2024-08-14 06:03
Also, you just leaked your steam account token, and you should change that, make a new one.

**Comment by 1zc** [comment] 2024-08-14 06:05
(I've just edited it out of your issue, but please create a new token for future use as it has been posted publicly)

Closing as this is not caused by the image/egg.

**Closed as completed by 1zc** 2024-08-14 06:05 UTC
Labels: not relevant to image
